/*
CREATE DATABASE TESTE;

USE TESTE;
*/

CREATE TABLE Usuario(
cpf VARCHAR (255) PRIMARY KEY NOT NULL,
email VARCHAR (255) NOT NULL,
senha VARCHAR(255) NOT NULL,
nomeCompleto VARCHAR(255) NOT NULL,
telefone VARCHAR(255) NOT NULL
);

CREATE TABLE Motorista(
idMotorista INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
cnh VARCHAR(255) NOT NULL
);

CREATE TABLE Usuario_Motorista(
cpf VARCHAR (255) PRIMARY KEY NOT NULL,
idMotorista INT NOT NULL AUTO_INCREMENT,
cnh VARCHAR(255) NOT NULL,
telefone VARCHAR(255) NOT NULL,
nomeCompleto VARCHAR(255) NOT NULL,
FOREIGN KEY (cpf) REFERENCES Usuario(cpf),
FOREIGN KEY (idMotorista) REFERENCES Motorista(idMotorista),
FOREIGN KEY (cnh) REFERENCES Motorista(cnh),
FOREIGN KEY (telefone) REFERENCES Usuario(telefone),
FOREIGN KEY (nomeCompleto) REFERENCES Usuario(nomeCompleto)
);

CREATE TABLE Filial(
idFilial INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nomeFilial VARCHAR(255) NOT NULL,
cnpj VARCHAR (255) NOT NULL,
endereco VARCHAR(255) NOT NULL,
numero INT NOT NULL,
complemento INT,
cep VARCHAR (255) NOT NULL,
bairro VARCHAR(255) NOT NULL,
uf VARCHAR(255) NOT NULL,
quantidadeVeiculos INT NOT NULL,
cota FLOAT NOT NULL
);

CREATE TABLE Cliente(
cpf VARCHAR(255) NOT NULL,
idCliente INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FOREIGN KEY (cpf) REFERENCES Usuario(cpf)
);

CREATE TABLE Funcionario(
matricula INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
cpf VARCHAR(255) NOT NULL,
cnpj VARCHAR(255) NOT NULL,
cargo VARCHAR(255) NOT NULL,
FOREIGN KEY (cpf) REFERENCES Usuario(cpf)
);

CREATE TABLE Reserva(
idReserva INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
dataReserva DATE NOT NULL,
dataDevolucao DATE NOT NULL,
valorPago VARCHAR(255) NOT NULL
);

CREATE TABLE Reserva_Cliente(
idReserva INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
cpf VARCHAR(255) NOT NULL,
valorPago VARCHAR(255) NOT NULL,
FOREIGN KEY (cpf) REFERENCES Usuario(cpf),
FOREIGN KEY (idReserva) REFERENCES Reserva(idReserva),
FOREIGN KEY (valorPago) REFERENCES Reserva(valorPago)
);


CREATE TABLE NotaFiscal(
idNF INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
numeroNF VARCHAR(255) NOT NULL,
dataEmissao DATE NOT NULL
);

CREATE TABLE Veiculo(
idVeiculo INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
placa VARCHAR(255) NOT NULL,
cnpj VARCHAR (255) NOT NULL,
idMotorista INT NOT NULL AUTO_INCREMENT,
marca VARCHAR(255) NOT NULL,
categoria VARCHAR(255) NOT NULL,
cor VARCHAR(255) NOT NULL,
quilometragem VARCHAR(255) NOT NULL,
ano VARCHAR(255) NOT NULL,
modelo VARCHAR(255) NOT NULL,
FOREIGN KEY (cnpj) REFERENCES Filial(cnpj),
FOREIGN KEY (idMotorista) REFERENCES Motorista(idMotorista)
); 

CREATE TABLE Contrato(
idContrato INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
placa VARCHAR(255) NOT NULL,
cnpj VARCHAR(255) NOT NULL,
cpf VARCHAR(255) NOT NULL,
nomeCompleto VARCHAR(255) NOT NULL,
dataEmissao DATE NOT NULL,
FOREIGN KEY (placa) REFERENCES Veiculo(placa),
FOREIGN KEY (cnpj) REFERENCES Filial(cnpj),
FOREIGN KEY (cpf) REFERENCES Usuario(cpf)
);

CREATE TABLE Estacao(
idEstacao INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
endereco VARCHAR(255) NOT NULL,
numero INT NOT NULL,
cep VARCHAR(255) NOT NULL,
statusEstacao VARCHAR(255) NOT NULL
);

CREATE TABLE Manutencao(
idManutencao INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
cpf VARCHAR(255) NOT NULL,
idEstacao INT AUTO_INCREMENT NOT NULL,
placa VARCHAR(255) NOT NULL,
dataEntrada DATE NOT NULL,
dataSaida DATE NOT NULL,
FOREIGN KEY (cpf) REFERENCES Usuario(cpf),
FOREIGN KEY (idOficina) REFERENCES Oficina(idOficina),
FOREIGN KEY (placa) REFERENCES Veiculo(placa)
);

